### ISSUE TITLE
C++11 & HPP_ASSERT

### ISSUE THREAD

**Issue by DianeBury** [humanoid-path-planner/hpp-util#16]
Hi,

There is an issue using HPP_ASSERT on boost::shared_ptr with C++11, raising en error during the compilation of hpp-manipulation because of a failed conversion to bool.

Line causing the error in hpp-manipulation:
https://github.com/humanoid-path-planner/hpp-manipulation/blob/6e38ce3a838ff365ec0941be881ec4760e407ef6/src/manipulation-planner.cc#L163

Because of the definition of macro HPP_ASSERT here:
https://github.com/humanoid-path-planner/hpp-util/blob/46c057eac4564173ad8ad64a6596e4e5a6bb1436/include/hpp/util/assertion.hh#L36

Indeed, in C++11, [as stated here](https://stackoverflow.com/questions/7580009/gcc-error-cannot-convert-const-shared-ptr-to-bool-in-return), the bool operator is implicit, so the cast fails. Adding an explicit cast would solve the issue.

**Comment by jmirabel** [comment]
You can change the line you mentioned by `bool _x = static_cast<bool>(CONDITION);`
