### ISSUE TITLE
[Compatibility Issue] Boost >=1.86

### ISSUE THREAD

**Issue by ymontmarin** [humanoid-path-planner/hpp-util#70]
I raised this issue, to inform that there are some compatibility issues with the last release of Boost (1.86).

The issue was raised during a boost migration on Conda : https://github.com/conda-forge/hpp-util-feedstock/pull/18

It looks related to the use of method `parent_path` following [Filesystem Deprecated Features](https://www.boost.org/doc/libs/1_86_0/libs/filesystem/doc/deprecated.html#Deprecated-names)

**Comment by nim65s** [comment]
This was fixed in #68
